### ISSUE TITLE
multiple ImageMarker are not always drawn

### ISSUE THREAD

**Issue by proppy** [DamonOehlman/tile5#51]
When adding multiple ImageMarker to map.markers, only the first one is drawn.

See:
http://playground.mekensleep.com/~proppy/tile5markerbug

By tracing tile5 code, I found out that marker.image was null for most of the marker when running T5.ImageMarker.drawMarker.

Preloading the image using T5.Images.get workaround this issue,

See:
http://playground.mekensleep.com/~proppy/tile5markerfix/

PS, I also found the following issue in ImageMarker code:
    --- tile5markerbug/vendor/tile5/dist/tile5.js   2010-12-09 11:14:23.000000000 +0000
    +++ tile5markerfix/vendor/tile5/dist/tile5.js   2010-12-09 11:57:46.000000000 +0000
    @@ -6301,7 +6301,7 @@
         } // if

```
     if (! self.animatingImage) {
-        self.animatingImage = T5.Images.get(params.imageUrl, function(image) {
+        self.animatingImage = T5.Images.get(params.animatingImageUrl, function(image) {
             self.animatingImage = image;
         });
     } // if
```

**Comment by proppy** [comment]
Looks like your latest changeset correct this issue:
https://github.com/sidelab/tile5/commit/a83ddd8f7a9fb40b286419aca4c15527624367c5

See:
http://playground.mekensleep.com/~proppy/tile5markerbugfix/

**Comment by DamonOehlman** [comment]
This has been fixed.
